#!/usr/bin/bash

# Matt Volpe
# CST 240
# HW 2 (Formerly Lab 5)
# May 19, 2020

# Unless stated otherwise
#  - the searches must be case insensitive
#  - All .txt and .csv files must be searched
#
# Each problem describes what you are searching for, it is your task to
# write a grep command that will find them.
#
# The correct number of found items is listed to help you know if you have
# the right answer.  You can use a pipe and the wc command to count the
# number of lines returned by grep.

# SAMPLE
# Use the grep command to find the word 'TIME' in any .txt or .csv file in
# the current directory. Case does not matter.
#
# -E uses extended syntax (not needed here)
# -i case-insensitive search
# -w whole word only ('sometimes' won't match)
#grep -Eiw TIME *.txt *.csv


# PROBLEM 1 (59 found)
# Find all years from 1900-199
grep 19[0-9][0-9] *.* | wc

# PROBLEM 2 (103 found)
# Find all years from 1900-2099
grep -Ew "(19|20)[0-9][0-9]" *.* | wc

# PROBLEM 3 (70 found)
# With out using the w option, find all instances of the word old
grep -i [[:blank:][:punct:][:space:]]old[[:blank:][:punct:][:space:]] *.* | wc

# PROBLEM 4 (17 found)
# Anything that looks like a letter grade inside of double quotes
# Uppercase letters only and may or may not have a + op - following it
grep -E "\"([A-D]|F)(\+|-)?\"" *.* | wc

# PROBLEM 5 (16 found)
# All words that begin with a vowel and end with 'it' in wordlist.txt
grep -Eiw "(a|e|i|o|u|y)[[:alpha:]]*it$" wordlist.txt | wc
# Didn't include y. But, you know, you can, I suppose, if you really want to.

# PROBLEM 6 (6 found)
# All in wordlist.txt words that do not begin with a vowel but end with
# 'es' and are at least 7 characters in length
grep -Eiw "[b-df-hj-np-tv-z][[:alpha:]]{4,}es$" wordlist.txt | wc
# Could have done [b-z&&[^eiou]][[:alpha:]]{4,}es$

# PROBLEM 7 (30 found)
# Find all dollar amounts with optional cents
# ($ followed by digits with one possible .)
grep "\\$""[0-9]\+\(\\.[0-9][0-9]\)\?" *.* | wc
